//PRODUCTS
//products
export const SET_PRODUCTS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

//single products
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT_SUCCESS";
export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const SET_SINGLE_PRODUCT_ERROR = "SET_SINGLE_PRODUCT_ERROR";

//filtered products
export const SET_FILTERED = "SET_FILTERED_SUCCESS";
export const PRICE_DESCENDING = "PRICE_DESCENDING";
export const PRICE_ASCENDING = "PRICE_ASCENDING";
export const NAME_DESCENDING = "NAME_DESCENDING";
export const NAME_ASCENDING = "NAME_ASCENDING";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_SORT = "UPDATE_SORT";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

//user

export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_USER = "SET_USER";
export const SET_USER_FROM_LOCAL_STORAGE = "SET_USER_FROM_LOCAL_STORAGE";

//cart items
export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const SET_CART = "SET_CART";
export const SET_CART_LOADING = "SET_CART_LOADING";
export const EDIT_CART_ITEM = "EDIT_CART_ITEM";
export const EDIT_CART_ITEM_LOADING = "EDIT_CART_ITEM_LOADING";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
