//PRODUCTS
//products
export const SET_PRODUCTS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

//single products
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT_SUCCESS";
export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const SET_SINGLE_PRODUCT_ERROR = "SET_SINGLE_PRODUCT_ERROR";

//filtered products
export const SET_FILTERED = "SET_FILTERED_SUCCESS";
export const PRICE_DESCENDING = "PRICE_DESCENDING";
export const PRICE_ASCENDING = "PRICE_ASCENDING";
export const NAME_DESCENDING = "NAME_DESCENDING";
export const NAME_ASCENDING = "NAME_ASCENDING";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_SORT = "UPDATE_SORT";
